### ISSUE TITLE
dummy image upload

### ISSUE THREAD

**Issue by jutanke** [jutanke/mocap#1]
![mocap_simplified](https://user-images.githubusercontent.com/831215/56189771-109a8b00-6029-11e9-9aed-d5b7278ed644.png)

**Comment by jutanke** [comment]
<img width="198" alt="Screenshot 2019-12-27 at 19 58 32" src="https://user-images.githubusercontent.com/831215/71535250-565f6100-28e3-11ea-8a0b-232e9dce3fa4.png">

**Comment by jutanke** [comment]
<img width="188" alt="Screenshot 2019-12-28 at 11 13 00" src="https://user-images.githubusercontent.com/831215/71544883-19d34a00-2963-11ea-8c21-03ea411ac17c.png">

**Comment by jutanke** [comment]
<img width="164" alt="Screenshot 2020-01-10 at 15 23 35" src="https://user-images.githubusercontent.com/831215/72164251-40f73600-33bd-11ea-9653-b5a12adf5720.png">

**Comment by jutanke** [comment]
![labels](https://user-images.githubusercontent.com/831215/72436240-44653580-37a0-11ea-85ee-def425e75f3c.png)

**Comment by jutanke** [comment]
<img width="204" alt="Screenshot 2020-02-29 at 16 43 30" src="https://user-images.githubusercontent.com/831215/75610569-b2787880-5b12-11ea-801a-ec52dd0f5af0.png">

**Comment by jutanke** [comment]
![image](https://user-images.githubusercontent.com/831215/82733026-42dce880-9d11-11ea-8cae-cfe724c0e16f.png)

**Comment by jutanke** [comment]
![image](https://user-images.githubusercontent.com/831215/82752978-55632a80-9dc2-11ea-9089-314742f59a80.png)

**Comment by jutanke** [comment]
![image](https://user-images.githubusercontent.com/831215/82758314-15ae3a00-9de6-11ea-9811-5d0c2be27f2b.png)

**Comment by jutanke** [comment]
![image](https://user-images.githubusercontent.com/831215/115024484-6f1ccd00-9ec0-11eb-9794-17a7f850e571.png)

**Comment by zhangjinrong731** [comment]
Hello, the picture of the human3.6m dataset is not very clear. Could you give a table corresponding to joints and labels? Thanks.
