### ISSUE TITLE
CMU_Eval Visualization

### ISSUE THREAD

**Issue by mertmerci** [jutanke/mocap#10]
Hello, 

I could not mange to visualise the CMU_eval. I get the error `Not Implemented` because the number of joints in this data is 39. How should I visualise it? 

Thanks in advance.

**Comment by jutanke** [comment]
The CMU_Eval data has 38 joints and can be plotted using the tool:
![image](https://user-images.githubusercontent.com/831215/169555963-f2be4bab-efa5-4f64-826c-83c6da067fe6.png)

Are you sure you're using the right data?

**Comment by mertmerci** [comment]
I can use the data with `CMU_EVAL.CMUEval3D` but not with `CMU_EVAL.CMUEval.` The problem is solved for now but just curios about why the former did not work.

**Comment by jutanke** [comment]
Oh, now I understand what was the problem: ```CMU_EVAL.CMUEval``` contains rotational data so to render this you will have to first project those to 3D coordinates using forward kinematics. To do that you can simply use the function
``` python
from mocap.math.fk_cmueval import angular2euclidean

seq3d = angular2euclidean(seq_angular)
```
but I would suggest to just use ```CMUEval3D``` if you are interested in the Euclidean representation.
