### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by oarriaga** [jutanke/mocap#2]
Hi,

I looked at the `pak` requirement and it seems that it's only used for loading the datasets which are again very modular e.g. requiring only `cv2` and `h5py`

Would you consider making this repo a stand-alone solution?

thank you for this great implementation!

**Comment by jutanke** [comment]
This might happen in a future version as it should not contain much overhead

**Comment by oarriaga** [comment]
OK thank you I will close this for now.
