### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by mertmerci** [jutanke/mocap#9]
Hello,

Thank you for the great repository. I faced with a problem during installation of spacepy. When I enter the command `wget -r -l1 -np -nd -nc http://cdaweb.gsfc.nasa.gov/pub/software/cdf/dist/latest-release/linux/ -A cdf*-dist-all.tar.gz` to the terminal,  I get `zsh: no matches found: cdf*-dist-all.tar.gz`. I searched for it but could not find anything. 

Do you have any suggestions for me? 

Thank you in advance.

**Comment by mertmerci** [comment]
Okay now I solved it with basically adding a new folder with the name`cdf*-dist-all.tar.gz`. However I do not understand where should I add the following `export...` lines.

**Comment by jutanke** [comment]
On what OS are you on? Ubuntu?

Note that you need spacepy only for the Human3.6M data.

You open your ```/home/{username}/.bashrc``` (or whatever console you're using) with the editor of your choice and then you simply add the export statements:

**Super important**: make sure to NOT delete anything that's in that file!

```
export CDF_BASE=$HOME/Libraries/cdf/cdf38_1-dist
export CDF_INC=$CDF_BASE/include
export CDF_LIB=$CDF_BASE/lib
export CDF_BIN=$CDF_BASE/bin
export LD_LIBRARY_PATH=$CDF_BASE/lib:$LD_LIBRARY_PATH
```

then you either ```source ~/.bashrc``` in your existing bash or you open a new bash. That should be it! And now you can use the H36M rotational data as well :) 

*SUPER IMPORTANT*: the current version of cdf ```38_1``` [link](https://cdaweb.gsfc.nasa.gov/pub/software/cdf/dist/latest-release/linux/)

**Comment by mertmerci** [comment]
I am using MacOS. Thank you for the brief explanation, for now I am using CMU dataset but if I use Human3.6M data I will consider it. I think we can close the issue for now.
